// Known disposable / throwaway email domains. Not exhaustive, but covers the
// common ones guests use to dodge a marketing list. Add more as you spot them.
const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "sharklasers.com",
  "grr.la",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "tempmail.com",
  "temp-mail.org",
  "tempmail.net",
  "temp-mail.io",
  "throwawaymail.com",
  "throwaway.email",
  "getnada.com",
  "nada.email",
  "trashmail.com",
  "trashmail.net",
  "mailnesia.com",
  "maildrop.cc",
  "dispostable.com",
  "yopmail.com",
  "yopmail.net",
  "fakeinbox.com",
  "fakemail.net",
  "mytemp.email",
  "mohmal.com",
  "emailondeck.com",
  "spamgourmet.com",
  "mintemail.com",
  "tempinbox.com",
  "mailcatch.com",
  "inboxbear.com",
  "burnermail.io",
  "33mail.com",
  "spam4.me",
  "tempr.email",
  "discard.email",
  "moakt.com",
  "luxusmail.org",
  "wegwerfmail.de",
  "einrot.com",
  "tempmailo.com",
  "cs.email",
  "gmailnator.com",
  "emailfake.com",
  "mailpoof.com",
]);

export function isDisposableDomain(domain) {
  return DISPOSABLE_DOMAINS.has((domain || "").toLowerCase());
}
