// Getting every signup onto the Google Sheet, exactly once.
//
// The hard part isn't sending the row — it's knowing whether it arrived.
// Apps Script answers a POST with a 302 pointing at its own output URL, and
// that second hop frequently fails even though the append succeeded. So the
// POST result is not trustworthy in either direction:
//
//   "looks like it failed" may have actually written the row  -> retrying
//                                                               would duplicate
//   "looks like it worked" may have thrown inside the script  -> settling
//                                                               would lose it
//
// Both are solved by not believing the POST:
//
//   1. the entry is queued to disk before the guest gets a response
//   2. the row is appended (the append itself is idempotent server-side)
//   3. a GET read-back confirms the row exists — GET responses come back
//      cleanly, which is how the dashboard reads the sheet
//   4. only a confirmed row is removed from the queue
//
// Anything unconfirmed stays queued and is retried by the poller. The result
// is that a crash, a restart, a Sheets outage or a quota block delays a row;
// it never loses one, and never writes it twice.

const { pending, settle, noteFailure } = require("./pending-sheet");

const WEBHOOK_TIMEOUT_MS = 15000;
const VERIFY_TIMEOUT_MS = 20000;
// Keep the verify URL comfortably short — these are 24-char timestamps.
const VERIFY_BATCH = 40;

function webhookUrl() {
  return process.env.GOOGLE_SHEETS_WEBHOOK_URL || "";
}

/** Append one signup. Resolves on an apparent success; never trust it alone. */
async function appendRow(entry) {
  const webhook = webhookUrl();
  if (!webhook) throw new Error("GOOGLE_SHEETS_WEBHOOK_URL not set");

  const res = await fetch(webhook, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(entry),
    redirect: "manual",
    signal: AbortSignal.timeout(WEBHOOK_TIMEOUT_MS),
  });
  // 2xx = direct reply, 3xx = the script ran and is redirecting to its output.
  if (res.status >= 200 && res.status < 400) return true;
  throw new Error(`Sheets webhook returned HTTP ${res.status}`);
}

/**
 * Which of these timestamps are on the sheet? Returns a Set.
 *
 * Only timestamps are sent — they're generated by this server and identify a
 * row, so no guest details end up in a query string.
 */
async function verifyTimestamps(timestamps) {
  const webhook = webhookUrl();
  const readKey = process.env.SHEETS_READ_KEY || "";
  if (!webhook) throw new Error("GOOGLE_SHEETS_WEBHOOK_URL not set");
  if (!readKey) throw new Error("SHEETS_READ_KEY not set");
  if (!timestamps.length) return new Set();

  const found = new Set();
  for (let i = 0; i < timestamps.length; i += VERIFY_BATCH) {
    const batch = timestamps.slice(i, i + VERIFY_BATCH);
    const url =
      `${webhook}?action=verify&key=${encodeURIComponent(readKey)}` +
      `&ts=${encodeURIComponent(batch.join(","))}`;
    const res = await fetch(url, {
      redirect: "follow",
      cache: "no-store",
      signal: AbortSignal.timeout(VERIFY_TIMEOUT_MS),
    });
    if (!res.ok) throw new Error(`Sheets verify returned HTTP ${res.status}`);
    const data = await res.json();

    // An Apps Script deployment older than this feature doesn't know the
    // action and falls through to its health check ({ ok: true, service }).
    // Distinguish that from a real failure so the caller can degrade instead
    // of refusing to write anything at all.
    if (!data.success && !Array.isArray(data.found)) {
      const err = new Error("Sheets verify action not available");
      err.verifyUnsupported = true;
      throw err;
    }
    if (!data.success) throw new Error(data.error || "Sheets verify failed");
    for (const ts of data.found || []) found.add(ts);
  }
  return found;
}

/**
 * Push queued signups to the sheet and settle only what's confirmed there.
 *
 * Safe to call concurrently with itself — the append is idempotent and
 * settling an already-settled entry is a no-op.
 *
 * @param {object}  opts
 * @param {number}  opts.limit   max entries per pass
 * @param {object}  opts.enrich  optional { [timestamp]: { deviceName, vendor } }
 * @returns {Promise<{attempted:number, saved:number, stillPending:number}>}
 */
async function flushQueue({ limit = 25, enrich = {} } = {}) {
  const queue = pending();
  if (!queue.length) return { attempted: 0, saved: 0, stillPending: 0 };

  const batch = queue.slice(0, limit);

  // Ask first. A previous attempt may have landed without us knowing, and
  // re-appending those is exactly how duplicates appear.
  let alreadyThere = new Set();
  let unverified = false;
  try {
    alreadyThere = await verifyTimestamps(batch.map((e) => e.entry.timestamp));
  } catch (err) {
    if (err && err.verifyUnsupported) {
      // The Apps Script hasn't been redeployed with the verify action yet.
      // Refusing to write would mean no signups reach the sheet at all, which
      // is far worse than the old best-effort behaviour — so fall back to
      // append-and-trust and say so loudly. Redeploying restores the
      // exactly-once guarantee with no other change.
      console.error(
        "Apps Script has no 'verify' action — redeploy apps-script/Code.gs to " +
          "guarantee every signup lands. Falling back to unverified appends."
      );
      unverified = true;
    } else {
      // A transient read failure. Appending blind here risks duplicates, so
      // stop and retry later; the rows stay queued, which is the safe
      // direction.
      console.error("Sheets verify unavailable, deferring flush:", String(err));
      return { attempted: 0, saved: 0, stillPending: queue.length };
    }
  }

  let saved = 0;
  let attempted = 0;

  for (const item of batch) {
    const ts = item.entry.timestamp;

    if (alreadyThere.has(ts)) {
      settle(item.id); // confirmed on the sheet — done
      saved += 1;
      continue;
    }

    attempted += 1;
    const extra = enrich[ts] || {};
    try {
      await appendRow({
        ...item.entry,
        deviceName: extra.deviceName || item.entry.deviceName || "",
        vendor: extra.vendor || item.entry.vendor || "",
      });
      // Without verification the POST result is all we have to go on. It's
      // the pre-existing behaviour, and better than never writing.
      if (unverified) {
        settle(item.id);
        saved += 1;
      }
    } catch (err) {
      noteFailure(item.id);
      console.error(`Sheet append failed for ${item.id}:`, String(err));
      // Sheets looks unhealthy — stop rather than hammer it. Everything
      // outstanding is still queued.
      break;
    }
  }

  if (unverified) {
    return { attempted, saved, stillPending: pending().length };
  }

  // Confirm the appends we just made. Anything unconfirmed stays queued and
  // will be verified again next pass rather than blindly re-sent now.
  const unsettled = pending();
  const toCheck = unsettled
    .filter((e) => batch.some((b) => b.id === e.id))
    .map((e) => e.entry.timestamp);

  if (toCheck.length) {
    try {
      const nowThere = await verifyTimestamps(toCheck);
      for (const item of unsettled) {
        if (nowThere.has(item.entry.timestamp)) {
          settle(item.id);
          saved += 1;
        }
      }
    } catch (err) {
      console.error("Post-append verify failed, leaving rows queued:", String(err));
    }
  }

  return { attempted, saved, stillPending: pending().length };
}

/** Queue health, for the admin panel and the poller's logs. */
function queueHealth() {
  const queue = pending();
  if (!queue.length) return { count: 0, oldestAgeMs: 0, maxAttempts: 0 };
  let oldest = Infinity;
  let maxAttempts = 0;
  for (const e of queue) {
    const t = new Date(e.queuedAt).getTime();
    if (!isNaN(t) && t < oldest) oldest = t;
    maxAttempts = Math.max(maxAttempts, e.attempts || 0);
  }
  return {
    count: queue.length,
    oldestAgeMs: oldest === Infinity ? 0 : Date.now() - oldest,
    maxAttempts,
  };
}

module.exports = { appendRow, verifyTimestamps, flushQueue, queueHealth };
