/**
 * HyperGlow Guest WiFi — Google Sheets webhook
 *
 * Setup:
 * 1. Create a Google Sheet (e.g. "HyperGlow WiFi Signups").
 * 2. Extensions -> Apps Script, delete any code there, paste this file.
 * 3. Click Deploy -> New deployment -> type: Web app
 *      - Execute as: Me
 *      - Who has access: Anyone
 * 4. Click Deploy, authorize when prompted, and copy the Web app URL.
 * 5. Put that URL in the splash server's .env as GOOGLE_SHEETS_WEBHOOK_URL.
 *
 * Handles two actions:
 *   (default)         append a new signup row
 *   updateDuration    find the row by Timestamp + Device MAC and fill in
 *                     "Disconnected" + "Total Time" (called by the poller)
 */

var HEADERS = [
  "Timestamp",       // A
  "Email",           // B
  "Name",            // C
  "Phone",           // D
  "Birthday",        // E  (DD/MM/YYYY)
  "Device MAC",      // F
  "AP MAC",          // G
  "SSID",            // H
  "Branch",          // I
  "Promo Offers",    // J
  "Disconnected",    // K
  "Total Time",      // L
  "Device Name",     // M
  "Vendor",          // N
];

var COL_TIMESTAMP = 1; // A
var COL_MAC = 6;       // F
var COL_DISCONNECTED = 11; // K
var COL_DURATION = 12;     // L
var COL_DEVICE_NAME = 13;  // M
var COL_VENDOR = 14;       // N

function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheets()[0];

    // Create header row on first use
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(HEADERS);
      sheet.getRange(1, 1, 1, HEADERS.length).setFontWeight("bold");
      sheet.setFrozenRows(1);
    }

    if (data.action === "updateDuration") {
      return handleUpdate(sheet, data);
    }

    // Default: append a new signup row.
    //
    // Idempotent on purpose. The server can't always tell whether an append
    // landed — Apps Script answers with a 302 to its output URL, and that
    // second hop often fails even when the write succeeded — so it retries
    // anything it couldn't confirm. Without this check a retry would add a
    // second copy of the same visit.
    if (data.timestamp && findRowByKey(sheet, data.timestamp, data.mac) > 0) {
      return json({ success: true, duplicate: true });
    }

    sheet.appendRow([
      data.timestamp || new Date().toISOString(),
      data.email || "",
      data.firstName || "",
      // Leading apostrophe keeps phone numbers/birthdays as text
      // so Sheets doesn't strip leading zeros or parse dates.
      data.phone ? "'" + data.phone : "",
      data.birthday ? "'" + data.birthday : "",
      data.mac || "",
      data.ap || "",
      data.ssid || "",
      data.branch || "",
      data.promo || "",
      "", // Disconnected (filled later by the poller)
      "", // Total Time
      data.deviceName || "",
      data.vendor || "",
    ]);

    return json({ success: true });
  } catch (err) {
    return json({ success: false, error: String(err) });
  }
}

/**
 * Row number for a signup, by Timestamp (+ MAC when given), or 0 if absent.
 *
 * Timestamps are generated by the splash server at millisecond precision, so
 * they identify a row on their own; the MAC is checked too when supplied.
 * Scans bottom-up because anything being looked up is almost always recent.
 */
function findRowByKey(sheet, timestamp, mac) {
  var last = sheet.getLastRow();
  if (last < 2) return 0;

  var keyTs = String(timestamp || "");
  if (!keyTs) return 0;
  var keyMac = String(mac || "").toLowerCase();

  var values = sheet.getRange(2, 1, last - 1, COL_MAC).getValues(); // A..F

  for (var i = values.length - 1; i >= 0; i--) {
    var rowTs = toIso(values[i][COL_TIMESTAMP - 1]);
    if (rowTs !== keyTs) continue;
    if (keyMac) {
      var rowMac = String(values[i][COL_MAC - 1]).toLowerCase();
      if (rowMac !== keyMac) continue;
    }
    return i + 2; // account for header + 0-index
  }
  return 0;
}

/** Find the signup row by Timestamp + MAC and write disconnect + duration. */
function handleUpdate(sheet, data) {
  var rowNumber = findRowByKey(sheet, data.timestamp, data.mac);
  if (!rowNumber) return json({ success: false, error: "row not found" });

  sheet.getRange(rowNumber, COL_DISCONNECTED).setValue(data.disconnectedAt || "");
  sheet.getRange(rowNumber, COL_DURATION).setValue(data.duration || "");

  // Device name / vendor arrive late (UniFi fingerprints a device a few
  // minutes after it joins), so fill them in if we now have better data.
  if (data.deviceName) sheet.getRange(rowNumber, COL_DEVICE_NAME).setValue(data.deviceName);
  if (data.vendor) sheet.getRange(rowNumber, COL_VENDOR).setValue(data.vendor);

  return json({ success: true, updatedRow: rowNumber });
}

function json(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(
    ContentService.MimeType.JSON
  );
}

/**
 * GET endpoints.
 *   ?action=data&key=YOUR_KEY     → all rows as JSON (used by the admin dashboard)
 *   ?action=verify&key=…&ts=a,b,c → which of those timestamps are on the sheet
 *   (no params)                   → health check
 *
 * IMPORTANT: set READ_KEY below to a long random string and put the same
 * value in the splash server's .env as SHEETS_READ_KEY.
 */
var READ_KEY = "HyperGlowSplashPage@HG";

function doGet(e) {
  var params = (e && e.parameter) || {};

  if (params.action === "data") {
    if (params.key !== READ_KEY) {
      return json({ success: false, error: "unauthorized" });
    }
    var read = readAllRows();
    return json({
      success: true,
      rows: read.rows,
      source: read.source, // "clean" | "raw"
      cleanedAt: PropertiesService.getScriptProperties().getProperty("CLEAN_BUILT_AT") || "",
    });
  }

  // Which of these signups actually made it onto the sheet?
  //
  // A POST can't answer this reliably — Apps Script replies to a POST with a
  // 302 to its output URL and that hop often fails, so the server can't read
  // the result. GET responses come back cleanly (it's how the dashboard reads
  // rows), so confirmation happens here. Only server-generated timestamps are
  // sent; no guest details go in the query string.
  if (params.action === "verify") {
    if (params.key !== READ_KEY) {
      return json({ success: false, error: "unauthorized" });
    }
    var wanted = String(params.ts || "")
      .split(",")
      .map(function (s) { return s.trim(); })
      .filter(function (s) { return s; });
    if (!wanted.length) return json({ success: true, found: [] });

    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheets()[0];
    var last = sheet.getLastRow();
    if (last < 2) return json({ success: true, found: [] });

    // One read of column A, then set membership — far cheaper than a scan per
    // timestamp when a backlog is being drained.
    var col = sheet.getRange(2, COL_TIMESTAMP, last - 1, 1).getValues();
    var present = {};
    for (var i = 0; i < col.length; i++) {
      var iso = toIso(col[i][0]);
      if (iso) present[iso] = true;
    }

    var found = [];
    for (var j = 0; j < wanted.length; j++) {
      if (present[wanted[j]]) found.push(wanted[j]);
    }
    return json({ success: true, found: found });
  }

  return json({ ok: true, service: "HyperGlow WiFi signups webhook" });
}

/**
 * Every data row as an object keyed by our known columns.
 *
 * Reads the "Clean" tab when Cleanup.gs has produced one (de-duplicated,
 * test rows removed, store backfilled), otherwise falls back to the raw
 * signup tab so the dashboard never goes blank.
 *
 * Writes always go to the raw tab — it stays the untouched record of what
 * guests actually submitted.
 */
function readAllRows() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var clean = ss.getSheetByName("Clean");
  var useClean = clean && clean.getLastRow() > 1;
  var sheet = useClean ? clean : ss.getSheets()[0];
  var source = useClean ? "clean" : "raw";

  var last = sheet.getLastRow();
  if (last < 2) return { rows: [], source: source };

  var values = sheet.getRange(2, 1, last - 1, HEADERS.length).getValues();
  var out = [];
  for (var i = 0; i < values.length; i++) {
    var r = values[i];
    // Skip completely empty rows
    if (!r[0] && !r[1]) continue;
    out.push({
      timestamp: toIso(r[0]),
      email: String(r[1] || ""),
      firstName: String(r[2] || ""),
      phone: String(r[3] || ""),
      birthday: String(r[4] || ""),
      mac: String(r[5] || ""),
      ap: String(r[6] || ""),
      ssid: String(r[7] || ""),
      branch: String(r[8] || ""),
      promo: String(r[9] || ""),
      disconnected: toIso(r[10]),
      duration: String(r[11] || ""),
      deviceName: String(r[12] || ""),
      vendor: String(r[13] || ""),
    });
  }
  return { rows: out, source: source };
}

/** Sheets may hand back a Date object or a string; normalise to ISO text. */
function toIso(v) {
  if (!v) return "";
  if (Object.prototype.toString.call(v) === "[object Date]") {
    return v.toISOString();
  }
  return String(v);
}
